In [1]:
import numpy as np

#### Q1 a)

In [2]:
Q1_array = np.arange(1,17,1).reshape(4,4)
print(Q1_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Q1 b i)

[3 7 11 15]

#### Q1 ii)

[13 14]

#### Q1 iii)

$
\begin{bmatrix} 
\begin{bmatrix} 1 & 4 \end{bmatrix} \\
\begin{bmatrix} 5 & 8 \end{bmatrix} \\
\begin{bmatrix} 9 & 12 \end{bmatrix} \\
\begin{bmatrix} 13 & 16 \end{bmatrix} \\
\end{bmatrix}
$

#### Q1 iv)

$
\begin{bmatrix} 
\begin{bmatrix} 1 & 2 \end{bmatrix} \\
\begin{bmatrix} 5 & 6 \end{bmatrix} \\
\end{bmatrix}
$

#### Q1 v)

$
\begin{bmatrix} 1 & 6 & 11 \end{bmatrix} 
$

#### Q1 vi)

$
\begin{bmatrix} 1 & 4 & 9 & 16 \end{bmatrix} 
$

#### Q1 vii)

$
\begin{bmatrix} 4 & 8 & 12 & 16 \end{bmatrix} 
$

#### Q1 viii)

$
\begin{bmatrix} 
\begin{bmatrix} 4 & 6 \end{bmatrix} \\
\begin{bmatrix} 12 & 14 \end{bmatrix} \\
\end{bmatrix}
$

#### Q1 ix)

$
\begin{bmatrix} 
\begin{bmatrix} 1 & 5 \end{bmatrix} \\
\begin{bmatrix} 2 & 6 \end{bmatrix} \\
\begin{bmatrix} 3 & 7 \end{bmatrix}
\end{bmatrix}
$

#### Q1 x)

$
\begin{bmatrix} 
\begin{bmatrix} 1 & 2 \end{bmatrix} \\
\begin{bmatrix} 3 & 5 \end{bmatrix} \\
\begin{bmatrix} 6 & 7 \end{bmatrix}
\end{bmatrix}
$

#### Q1 xi)

$\begin{bmatrix} 3 & 11 & 19 & 27 \end{bmatrix}$

#### Q1 xii)

$
\begin{bmatrix} 
\begin{bmatrix} 3 & 4 \end{bmatrix} \\
\begin{bmatrix} 15 & 12 \end{bmatrix} \\
\begin{bmatrix} 27 & 20 \end{bmatrix} \\
\begin{bmatrix} 39 & 28 \end{bmatrix}
\end{bmatrix}
$

#### Q2 a)

In [5]:
Q2_x = np.array([[1,0],[0,1]])
Q2_y = np.array([[2,3],[4,5]])

Q2_z = np.vstack((np.hstack([Q2_x,Q2_x]),np.hstack([Q2_y,Q2_y])))
print(Q2_z)
print(Q2_z[:2,:2])



[[1 0 1 0]
 [0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]
[[1 0]
 [0 1]]


#### Q2 b)

We want a column vector: $\begin{bmatrix} x \\ y \end{bmatrix}$, as this would be the transpose of the row vector: $\begin{bmatrix} x' & y' \end{bmatrix}$.

i.e. $\begin{bmatrix} x' & y' \end{bmatrix}' = \begin{bmatrix} x \\ y \end{bmatrix}$

In [11]:
np.hstack([Q2_z[:2,:2].T, Q2_z[2:,2:].T]).T

array([[1, 0],
       [0, 1],
       [2, 3],
       [4, 5]])

Instead of the np.array.T command usage, an equivalent command would be to use the np.transpose() function.

We could also alternatively use any combination of the [0,1] & [1,0] indexes to select x & y from z, as z is symmetric.